-- Seed file to populate common Chinese Radicals in database
-- Location: supabase/seed.sql

INSERT INTO public.radicals (character, pinyin, vietnamese_name, stroke_count) VALUES
('⺀', 'bīng', 'Băng (nước đá)', 2),
('冖', 'mì', 'Mịch (trùm khăn lên)', 2),
('冫', 'bīng', 'Băng (nước đá)', 2),
('凵', 'khǎn', 'Khảm (há miệng)', 2),
('刀', 'dāo', 'Đao (con dao)', 2),
('力', 'lì', 'Lực (sức mạnh)', 2),
('勹', 'bāo', 'Bao (bao bọc)', 2),
('匕', 'bǐ', 'Chuỷ (cái thìa)', 2),
('匚', 'fāng', 'Phương (tủ đựng)', 2),
('匸', 'xì', 'Hệ (che đậy)', 2),
('十', 'shí', 'Thập (số mười)', 2),
('卜', 'bǔ', 'Bốc (xem bói)', 2),
('卩', 'jié', 'Tiết (đốt tre)', 2),
('厂', 'chǎng', 'Hán (sườn núi)', 2),
('厶', 'sī', 'Khư (riêng tư)', 2),
('又', 'yòu', 'Hựu (lại nữa)', 2),
('口', 'kǒu', 'Khẩu (cái miệng)', 3),
('囗', 'wéi', 'Vi (vây quanh)', 3),
('土', 'tǔ', 'Thổ (đất)', 3),
('士', 'shì', 'Sĩ (kẻ sĩ)', 3),
('夂', 'zhǐ', 'Truy (đi chậm)', 3),
('夕', 'xī', 'Tịch (buổi tối)', 3),
('大', 'dà', 'Đại (to lớn)', 3),
('女', 'nǚ', 'Nữ (con gái)', 3),
('子', 'zǐ', 'Tử (con cái)', 3),
('宀', 'mián', 'Miên (mái nhà)', 3),
('寸', 'cùn', 'Thốn (tấc)', 3),
('小', 'xiǎo', 'Tiểu (nhỏ bé)', 3),
('尢', 'yóu', 'Uông (yếu đuối)', 3),
('尸', 'shī', 'Thi (xác chết)', 3),
('屮', 'chè', 'Triệt (mầm non)', 3),
('山', 'shān', 'Sơn (núi)', 3),
('巛', 'chuān', 'Xuyên (sông ngòi)', 3),
('工', 'gōng', 'Công (công việc)', 3),
('己', 'jǐ', 'Kỷ (bản thân)', 3),
('巾', 'jīn', 'Cân (khăn lau)', 3),
('干', 'gān', 'Can (thiên can)', 3),
('幺', 'yāo', 'Yêu (nhỏ nhắn)', 3),
('广', 'guǎng', 'Quảng (mái nhà rộng)', 3),
('廴', 'yǐn', 'Dẫn (bước dài)', 3),
('廾', 'gǒng', 'Củng (chắp tay)', 3),
('弋', 'yì', 'Dặc (bắn cung)', 3),
('弓', 'gōng', 'Cung (cây cung)', 3),
('彐', 'jì', 'Ký (đầu con nhím)', 3),
('彡', 'shān', 'Sâm (lông dài)', 3),
('彳', 'chì', 'Sách (bước chân trái)', 3),
('心', 'xīn', 'Tâm (quả tim)', 4),
('戈', 'gē', 'Qua (cây mác)', 4),
('户', 'hù', 'Hộ (cánh cửa)', 4),
('手', 'shǒu', 'Thủ (bàn tay)', 4),
('支', 'zhī', 'Chi (nhánh cây)', 4),
('攴', 'pū', 'Phộc (đánh nhẹ)', 4),
('文', 'wén', 'Văn (văn chương)', 4),
('斗', 'dǒu', 'Đấu (cái đấu đong gạo)', 4),
('斤', 'jīn', 'Cân (rìu kéo)', 4),
('方', 'fāng', 'Phương (hướng vuông)', 4),
('无', 'wú', 'Vô (không có)', 4),
('日', 'rì', 'Nhật (mặt trời)', 4),
('曰', 'yuē', 'Viết (nói rằng)', 4),
('月', 'yuè', 'Nguyệt (mặt trăng)', 4),
('木', 'mù', 'Mộc (cây cối)', 4),
('欠', 'qiàn', 'Khiếm (thiếu thốn)', 4),
('止', 'zhǐ', 'Chỉ (dừng lại)', 4),
('歹', 'dǎi', 'Đãi (xấu xa)', 4),
('殳', 'shū', 'Thù (gậy dài)', 4),
('毋', 'wú', 'Vô (chớ, đừng)', 4),
('比', 'bǐ', 'Bỉ (so sánh)', 4),
('毛', 'máo', 'Mao (lông lá)', 4),
('氏', 'shì', 'Thị (dòng họ)', 4),
('气', 'qì', 'Khí (hơi nước)', 4),
('水', 'shuǐ', 'Thuỷ (nước)', 4),
('氵', 'shuǐ', 'Ba chấm thuỷ (nước)', 3),
('火', 'huǒ', 'Hỏa (lửa)', 4),
('灬', 'huǒ', 'Hỏa (bốn chấm lửa)', 4),
('爪', 'zhǎo', 'Trảo (móng vuốt)', 4),
('父', 'fù', 'Phụ (cha)', 4),
('爻', 'yáo', 'Hào (quẻ bói)', 4),
('爿', 'qiáng', 'Tường (mảnh gỗ dựng đứng)', 4),
('片', 'piàn', 'Phiến (mảnh gỗ nằm ngang)', 4),
('牙', 'yá', 'Nha (răng)', 4),
('牛', 'niú', 'Ngưu (con trâu)', 4),
('犬', 'quǎn', 'Khuyển (con chó)', 4)
ON CONFLICT (character) DO NOTHING;
