export const theme = {
  colors: {
    primary: "#059669",
    primaryShadow: "#047857",
    secondary: "#D97706",
    secondaryShadow: "#B45309",
    danger: "#DC2626",
    dangerShadow: "#991B1B",
    info: "#2563EB",
    infoShadow: "#1D4ED8",
    bg: "#F9FAFB",
    cardBg: "#FFFFFF",
    cardBorder: "#E5E7EB",
    textPrimary: "#111827",
    textSecondary: "#6B7280",
    textLight: "#9CA3AF",
    white: "#FFFFFF",
  },
  badges: {
    due: {
      bg: "#FEE2E2",
      text: "#DC2626",
      border: "#FCA5A5",
    },
    learned: {
      bg: "#D1FAE5",
      text: "#059669",
      border: "#6EE7B7",
    },
    new: {
      bg: "#E0F2FE",
      text: "#0284C7",
      border: "#BAE6FD",
    },
    warning: {
      bg: "#FEF3C7",
      text: "#D97706",
      border: "#FCD34D",
    },
    info: {
      bg: "#EFF6FF",
      text: "#2563EB",
      border: "#93C5FD",
    },
    neutral: {
      bg: "#F3F4F6",
      text: "#4B5563",
      border: "#E5E7EB",
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    hero: 40,
  },
  fontSize: {
    xs: 12,
    sm: 14,
    base: 16,
    lg: 18,
    xl: 20,
    xxl: 24,
    title: 28,
    hero: 64,
  },
  fontWeight: {
    regular: "400" as const,
    medium: "500" as const,
    semibold: "600" as const,
    bold: "700" as const,
    black: "900" as const,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  shadows: {
    sm: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 3,
    },
    lg: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.1,
      shadowRadius: 15,
      elevation: 5,
    },
  },
};

export type Theme = typeof theme;
